import React from 'react'
import {
  AccountBookOutlined,
  ApiOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BarChartOutlined,
  BellOutlined,
  CalendarOutlined,
  CloudServerOutlined,
  CompassOutlined,
  ControlOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  FileTextOutlined,
  FolderOutlined,
  FormOutlined,
  FundOutlined,
  HistoryOutlined,
  HomeOutlined,
  LineChartOutlined,
  LockOutlined,
  MenuOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  PartitionOutlined,
  PieChartOutlined,
  ProfileOutlined,
  ProjectOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  SolutionOutlined,
  TableOutlined,
  TagsOutlined,
  TeamOutlined,
  ToolOutlined,
  TransactionOutlined,
  UnorderedListOutlined,
  UserOutlined,
  WalletOutlined,
} from '@ant-design/icons'

export const MENU_ICON_OPTIONS = [
  { label: '首页', value: 'home' },
  { label: '工作台', value: 'dashboard' },
  { label: '应用', value: 'app' },
  { label: '菜单', value: 'menu' },
  { label: '列表', value: 'list' },
  { label: '表格', value: 'table' },
  { label: '表单', value: 'form' },
  { label: '文件', value: 'file' },
  { label: '资料', value: 'profile' },
  { label: '项目', value: 'project' },
  { label: '文件夹', value: 'folder' },
  { label: '图表', value: 'chart' },
  { label: '饼图', value: 'pie-chart' },
  { label: '折线图', value: 'line-chart' },
  { label: '经营分析', value: 'fund' },
  { label: '日历', value: 'calendar' },
  { label: '发现', value: 'compass' },
  { label: '日程', value: 'schedule' },
  { label: '历史', value: 'history' },
  { label: '账本', value: 'account-book' },
  { label: '钱包', value: 'wallet' },
  { label: '交易', value: 'transaction' },
  { label: '标签', value: 'tags' },
  { label: '门店', value: 'shop' },
  { label: '购物车', value: 'shopping-cart' },
  { label: '用户', value: 'user' },
  { label: '团队', value: 'team' },
  { label: '权限', value: 'lock' },
  { label: '安全', value: 'safety' },
  { label: '审计', value: 'audit' },
  { label: '通知', value: 'bell' },
  { label: '公告', value: 'notification' },
  { label: '设置', value: 'setting' },
  { label: '工具', value: 'tool' },
  { label: '控制台', value: 'control' },
  { label: '接口', value: 'api' },
  { label: '服务', value: 'cloud-server' },
  { label: '数据', value: 'database' },
  { label: '部署', value: 'deployment' },
  { label: '组织架构', value: 'partition' },
  { label: '流程节点', value: 'node-index' },
  { label: '解决方案', value: 'solution' },
]

const MENU_ICON_MAP = {
  home: HomeOutlined,
  dashboard: DashboardOutlined,
  app: AppstoreOutlined,
  menu: MenuOutlined,
  list: UnorderedListOutlined,
  table: TableOutlined,
  form: FormOutlined,
  file: FileTextOutlined,
  profile: ProfileOutlined,
  project: ProjectOutlined,
  folder: FolderOutlined,
  chart: BarChartOutlined,
  'pie-chart': PieChartOutlined,
  'line-chart': LineChartOutlined,
  fund: FundOutlined,
  calendar: CalendarOutlined,
  compass: CompassOutlined,
  schedule: ScheduleOutlined,
  history: HistoryOutlined,
  'account-book': AccountBookOutlined,
  wallet: WalletOutlined,
  transaction: TransactionOutlined,
  tags: TagsOutlined,
  shop: ShopOutlined,
  'shopping-cart': ShoppingCartOutlined,
  user: UserOutlined,
  team: TeamOutlined,
  lock: LockOutlined,
  safety: SafetyOutlined,
  audit: AuditOutlined,
  bell: BellOutlined,
  notification: NotificationOutlined,
  setting: SettingOutlined,
  tool: ToolOutlined,
  control: ControlOutlined,
  api: ApiOutlined,
  'cloud-server': CloudServerOutlined,
  database: DatabaseOutlined,
  deployment: DeploymentUnitOutlined,
  partition: PartitionOutlined,
  'node-index': NodeIndexOutlined,
  solution: SolutionOutlined,
}

export const renderMenuIcon = (icon) => {
  const Icon = MENU_ICON_MAP[icon] || AppstoreOutlined
  return React.createElement(Icon)
}
